### PR TITLE
Added Sapporo to our menu

### PR DESCRIPTION
**Pull request by wcniedba**
Issuing a Pull Request so that Sapporo Beer will appear on our national menus.

### CODE REVIEW

**Review by doughale — CHANGES_REQUESTED** [review]
We need to charge 5.50 for sapporo. Please update PR.

**Comment by wcniedba** [comment]
I changed the file, committed and pushed the commit to my fork.  Somehow it has magically associated my commit change to this PR.  I'm not sure how.  But I now see two Commits listed up above.  Is it because this PR is simply saying "Merge Chris's main into Doug's main" and that whatever commits are in my main when we click "Approve" go into it?

**Comment by doughale** [comment]
... "whatever commits are in my main when we click "Approve" go into it?" .. yes - correct. When you "fork", it tracks where you forked from.  I am merging this in .. not rebasing which is an option .. but merging.

**Comment by doughale** [comment]
Price looks good - confirming the PR and merging

**Pull request merged**
